### ISSUE TITLE
Extending to real time inference

### ISSUE THREAD

**Issue by ak3ra** [LukasHedegaard/co3d#10]
Hi, 

Great work here! Amazing suite and looks quite extensive. I am curious how you'd extend the data loaders and inference mechanisms to support direct inference on a live video stream. Happy to make a PR on this if not there already :) 
Additionally, what would be the steps to retrain on a custom video dataset ? 

Cheers

**Comment by LukasHedegaard** [comment]
Hi @ak3ra , thanks for the interest! 
You can do live video-stream processing efficiently with the "forward_step" function of the modules. I created a [live-processing example](https://github.com/opendr-eu/opendr/tree/master/projects/python/perception/activity_recognition/demos/online_recognition) a while back for the OpenDR toolkit which includes the CoX3D modules. It has an additional layer of abstraction (the CoX3DLearner), which was needed for toolkit compatibility, but the gist should be similar to using the unwrapped CoX3D class. Hope it helps :-)

**Comment by ak3ra** [comment]
Great, thanks! this is helpful and looks like exactly what I was looking for!
