### ISSUE TITLE
Are multiple streams possible for a single model?

### ISSUE THREAD

**Issue by Y-T-G** [LukasHedegaard/co3d#11]
Can you instantiate multiple states for this? Or is a single model supposed to only infer on the same video stream?

**Comment by LukasHedegaard** [comment]
Hi! 
If multiple video-streams are recorded in parallel with the same resolution and sampling rate, you can increase the batch size to the number of streams and pass multiple frames along the batch dimension. 

If they differ in resolution or sampling rate, you need to instantiate multiple models.

Hope this clears things up 😊

**Comment by Y-T-G** [comment]
@LukasHedegaard Thanks for the reply.

So I assume the order of batching is important then? For instance, if stream 1 and stream 2 was batched in the order [s1, s2], then I will also have to maintain that order in subsequent batches.

**Comment by LukasHedegaard** [comment]
Yes, exactly.

**Comment by Y-T-G** [comment]
Great. Thanks.
